shoe-portal/src/Octagon/ShoePortal/CustomerBundle/Entity/Categories.php
<?php

namespace Octagon\ShoePortal\CustomerBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Categories
 *
 * @ORM\Table(name="Categories", indexes={@ORM\Index(name="fk_Categories_Categories1_idx", columns={"idParent"})})
 * @ORM\Entity
 */
class Categories
{
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=45, nullable=false)
     */
    private $name;

    /**
     * @var integer
     *
     * @ORM\Column(name="level", type="integer", nullable=true)
     */
    private $level;

    /**
     * @var integer
     *
     * @ORM\Column(name="idCategories", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idCategories;

    /**
     * @var \Octagon\ShoePortal\CustomerBundle\Entity\Categories
     *
     * @ORM\ManyToOne(targetEntity="Octagon\ShoePortal\CustomerBundle\Entity\Categories")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="idParent", referencedColumnName="idCategories")
     * })
     */
    private $idParent;



    /**
     * Set name
     *
     * @param string $name
     * @return Categories
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set level
     *
     * @param integer $level
     * @return Categories
     */
    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * Get level
     *
     * @return integer 
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Get idCategories
     *
     * @return integer 
     */
    public function getIdCategories()
    {
        return $this->idCategories;
    }
    
     /**
     * Get idCategories base64 version
     *
     * @return string 
     */
    public function getIdCategoriesHash()
    {
        return base64_encode($this->idCategories);
    }

    /**
     * Set idParent
     *
     * @param \Octagon\ShoePortal\CustomerBundle\Entity\Categories $idParent
     * @return Categories
     */
    public function setIdCarent(\Octagon\ShoePortal\CustomerBundle\Entity\Categories $idParent = null)
    {
        $this->idParent = $idParent;

        return $this;
    }

    /**
     * Get idParent
     *
     * @return \Octagon\ShoePortal\CustomerBundle\Entity\Categories 
     */
    public function getIdParent()
    {
        return $this->idParent;
    }
    public function __toString() {
        return $this->name;
    }
}

shoe-portal/src/Octagon/ShoePortal/CustomerBundle/Controller/CategoriesController.php
<?php

namespace Octagon\ShoePortal\CustomerBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
/**
 * Description of CategoriesController
 *
 * @author rommen
 */
class CategoriesController extends Controller{
    
    public function listAction(Request $request){     
         $categories = $this->getDoctrine()
               ->getRepository('CustomerBundle:Categories')->findAll();
        return $this->render('CustomerBundle:Categories:list.html.twig', 
                array('categories'=>$categories, 
                    'categoryId'=>$request->get("categoryId")));
    }
}

shoe-portal/src/Octagon/ShoePortal/CustomerBundle/Resources/views/Categories/list.html.twig
<div id="categories" class="left">      
    <div class="list-group">
        <script>
            function click(category) {
                var url = window.location.href;
                var cIdIdx = url.indexOf("categoryId");
                var qi = url.indexOf("?");
                
                var href = null;
                if (qi >= 0) {
                    if (cIdIdx >= 0) {
                       url = url.replace(/(&?categoryId=[a-zA-Z=]*)/i,"");
                    }
                    href = url + "&categoryId=" + category;
                } else {
                    href = url + "?categoryId=" + category;
                }
                window.location.href = href;
                
            }
        </script>
        {%if '?' in app.request.getBaseUrl%}
            {%set base = app.request.getBaseUrl ~ "&categoryId="%}
        {%else%}
            {%set base = app.request.getBaseUrl ~ "?categoryId="%}
        {%endif%}
        {% for category in categories %}
            {%if categoryId != null and category.idCategoriesHash == categoryId%}
                <a class="list-group-item active" href="javascript:click('{{category.idCategoriesHash}}');">{{category.name}}</a>
            {%else%}
                <a class="list-group-item" href="javascript:click('{{category.idCategoriesHash}}');">{{category.name}}</a>
            {%endif%}
        {% endfor %}        
    </div>
</div>